/*
Copyright © 2025 Pablo Bidwell <bidwell.pablo@gmail.com>
*/
package cmd

import (
	"github.com/pbidwell/hippocurl/modules/log"

	"github.com/spf13/cobra"
)

// logCmd represents the log command
var logCmd = &cobra.Command{
	Use:   "log",
	Short: "Parse and display logs captured during HippoCurl requests",
	Long: `The 'log' module displays detailed logs generated by HippoCurl modules.
Use this command to review captured request/response data, timing metrics, 
and any module-specific debug information stored during previous executions.

Examples:
  hc log                       # View logs interactively`,
	Run: func(cmd *cobra.Command, args []string) {
		ExecuteModule(log.LogModule{}, args)
	},
}

func init() {
	rootCmd.AddCommand(logCmd)
}
