name: Build and Release HippoCurl

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write  # Ensures the workflow can create a release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24.1

      - name: Build Executables
        run: |
          VERSION=$(git describe --tags --always)
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -ldflags "-X main.version=$VERSION" -o dist/hippocurl-linux-amd64 ./main.go
          GOOS=darwin GOARCH=amd64 go build -ldflags "-X main.version=$VERSION" -o dist/hippocurl-mac-amd64 ./main.go
          GOOS=windows GOARCH=amd64 go build -ldflags "-X main.version=$VERSION" -o dist/hippocurl-windows-amd64.exe ./main.go

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
